### ISSUE TITLE
Colours messed up in Common Lisp

### ISSUE THREAD

**Issue by HiPhish** [p00f/nvim-ts-rainbow#101]
Hello,

The parentheses colours are all wrong in Common Lisp buffers. Here is a screenshot, the top buffer shows the expected colours (in Lua) for comparison.

![Screenshot_20220327_225211](https://user-images.githubusercontent.com/4954650/160300654-2c37f7b6-5f2a-4c35-9b53-ef86654cf014.png)

The first line in the Common Lisp buffer shows the correct colours, but the order is shifted by one, i.e. red is the last colour instead of the first. The second line it same. The third and fourth line is all wrong, it skips green and goes to orange instead. I guess it might have to do with the semantic highlighting of the `defun` form.

My configuration:

```lua
rainbow = {
	enable = true,
}
```

Below the call to the `setup` function I also have the following highlight links:

``` lua
vim.cmd 'hi link rainbowcol1 RainbowRed'
vim.cmd 'hi link rainbowcol2 RainbowYellow'
vim.cmd 'hi link rainbowcol3 RainbowBlue'
vim.cmd 'hi link rainbowcol4 RainbowGreen'
vim.cmd 'hi link rainbowcol5 RainbowOrange'
vim.cmd 'hi link rainbowcol6 RainbowCyan'
vim.cmd 'hi link rainbowcol7 RainbowViolet'
```

**Comment by p00f** [comment]
Common lisp has only round brackets so everything is a `list_lit`, correct ? (i.e. all lists are the same)

![image](https://user-images.githubusercontent.com/36493671/160301237-8e3299cf-1db1-47cb-8570-096f08a7999e.png)
It gets fixed for your example if I add
```diff
diff --git a/lua/rainbow/levels.lua b/lua/rainbow/levels.lua
index ffb3af3..54f52ee 100644
--- a/lua/rainbow/levels.lua
+++ b/lua/rainbow/levels.lua
@@ -132,4 +132,7 @@ return {
         bracket_index_expression = true,
         parenthesized_expression = true,
     },
+    commonlisp = {
+        list_lit = true,
+    },
 }
```

**Comment by HiPhish** [comment]
Looks good now.

> Common lisp has only round brackets so everything is a `list_lit`, correct ?
> (i.e. all lists are the same)

I am not familiar with Treesitter syntax (that's something I need to remedy), 
but yes, all lists in Common Lisp are the same. Well, technically it is 
possible to add new syntax through reader macros, but anyone who does that 
won't be expecting support for it from a static parser library.

**Comment by p00f** [comment]
thanks
