### ISSUE TITLE
Template literal colors for curly braces not matching in JavaScript.

### ISSUE THREAD

**Issue by lewpoly** [p00f/nvim-ts-rainbow#102]
When using template literals in JavaScript files, the opening and closing curly braces use different highlight colors.

![2022-04-02_13-11](https://user-images.githubusercontent.com/68481374/161393811-7ee4d308-016e-4852-9bb7-ec8738912857.png)

This happens whether or not there is one or many different variables in a template string.

Is there an option to make these match that I'm missing, or is this their intended behavior?

**Comment by p00f** [comment]
Fixed

**Comment by lewpoly** [comment]
And just like that! Thanks alot man that was quick.
