### ISSUE TITLE
Default color of brackets is red?

### ISSUE THREAD

**Issue by xy9485** [p00f/nvim-ts-rainbow#104]
The default color of bracket or the first layer of nested brackets is red which looks not so neat, as show in the screenshot. I find it's different with the color effect I've seen in some videos. Did I miss somewhere in config? 
![image](https://user-images.githubusercontent.com/37043390/162643447-904abc20-d185-49f7-b799-2207587d8542.png)

**Comment by p00f** [comment]
Yes, the first colour is red. You can change it

**Comment by p00f** [comment]
> red which looks not so neat

I just picked a set of colours from gruvbox, the user is expected to change it/use a colorscheme which changes it

**Comment by xy9485** [comment]
> I just picked a set of colours from gruvbox, the user is expected to change it/use a colorscheme which changes it

Thanks for the reply.  So just changing colorschemes can also change the default order of rainbow colors?

Since I'm a newbie to this plugin, I'm also not sure what's the format for the content to change the color setting below. Could you provide an small example?

```
require'nvim-treesitter.configs'.setup{
  rainbow = {
    -- Setting colors
    colors = {
      -- Colors here
    },
    -- Term colors
    termcolors = {
      -- Term colors here
    }
  },
}
```

**Comment by p00f** [comment]
https://github.com/p00f/nvim-ts-rainbow/blob/a62dc50becf8b0fb4348fe02029b49247f9f3db7/lua/rainbow.lua#L13-L30

**Comment by p00f** [comment]
> So just changing colorschemes can also change the default order of rainbow colors?

Some colorschemes support this plugin - https://sr.ht/~novakane/kosmikoa.nvim/, https://github.com/ishan9299/modus-theme-vim etc

**Comment by xy9485** [comment]
> https://github.com/p00f/nvim-ts-rainbow/blob/a62dc50becf8b0fb4348fe02029b49247f9f3db7/lua/rainbow.lua#L13-L30

I wonder if it works when only modifying `termcolors` and leaving `colors`  commented?

**Comment by p00f** [comment]
Termcolors is for terminal vim without guicolors - ie tty. You don't need that in modern terminals
>  Actually I tried both by changing the order, didn't change colors of brackets. Would colorschemes force the order of color?

paste your config please

**Comment by xy9485** [comment]
> Termcolors is for terminal vim without guicolors - ie tty. You don't need that in modern terminals
> 
> > Actually I tried both by changing the order, didn't change colors of brackets. Would colorschemes force the order of color?
> 
> paste your config please

```
  rainbow = {
    enable = true,
    -- disable = { "jsx", "cpp" }, list of languages you want to disable the plugin for
    extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
    max_file_lines = nil, -- Do not enable for files with more than n lines, int
    colors = {
      "#a89984",
      "#cc241d",
      "#b16286",
      "#d79921",
      "#689d6a",
      "#d65d0e",
      "#458588",
    }, -- table of hex strings
    -- termcolors = {
    --   "Red",
    --   "Green",
    --   "Yellow",
    --   "Blue",
    --   "Magenta",
    --   "Cyan",
    --   "White",
    -- }, -- table of colour name strings
  }
}
```
for example I wanted  to make green as the first choice, didn't work out.

**Comment by p00f** [comment]
https://github.com/olimorris/onedarkpro.nvim this? You can disable onedark highlighting using this https://github.com/olimorris/onedarkpro.nvim#configuring-plugins

This is the only way out, if I drop `default` https://github.com/p00f/nvim-ts-rainbow/blob/a62dc50becf8b0fb4348fe02029b49247f9f3db7/lua/rainbow/internal.lua#L138 here then users won't be able to manually override using `hi rainbowcol1..`

**Comment by xy9485** [comment]
Yes, correct link. I might not fully understand, to disable onedark highlighting by configuring onedarkpro's plugin support? Can you explain more detailed? Does this operation independently solve the problem on your side, or is that change in `internal.lua` additionally needed?  Honestly I prefer not to touch internal code since I don't want to make it ad-hoc. 
Btw, can I use this `hi rainbowcol1 guifg=#123456` in pure lua configuration

**Comment by p00f** [comment]
>  I might not fully understand, to disable onedark highlighting by configuring onedarkpro's plugin support? 
yes

you dont need to touch internal.lua, just set the colors in your config:   https://github.com/p00f/nvim-ts-rainbow#colours

**Comment by xy9485** [comment]
> You can disable onedark highlighting using this https://github.com/olimorris/onedarkpro.nvim#configuring-plugins

Sorry for my confussion on this point, I assume you refer to disabling nvim-ts-rainbow in onedarkpro's plugin configuration, is that correct?

**Comment by p00f** [comment]
yes

**Comment by xy9485** [comment]
So I disabled nvim-ts-rainbow in oneardkpro, it does make some changes, but still doesb't match the order. 
For example with the config you gave before:
```
colors = {
      "#cc241d", --red
      "#a89984", --grey
      "#b16286", --Magenta
      "#d79921", --yellow
      "#689d6a", --green
      "#d65d0e", --orange
      "#458588", --cyan
    }, 
```
![image](https://user-images.githubusercontent.com/37043390/162756369-81e22d14-1a34-4a66-8e02-184402a1d945.png)
 And looks like the color order remains same if I change the order in config:
```
colors = {
      "#a89984", --grey
      "#cc241d", --red
      "#b16286", --Magenta
      "#d79921", --yellow
      "#689d6a", --green
      "#d65d0e", --orange
      "#458588", --cyan
    }, 
```
![image](https://user-images.githubusercontent.com/37043390/162757214-7bc79582-7f94-4e12-a8c7-605365c9c930.png)

**Comment by p00f** [comment]
those colors look like onedark, not gruvbox are you sure you did
```lua
require("onedarkpro").setup({
    plugins = {nvim_ts_rainbow = false}
})
```
