### ISSUE TITLE
File type change not being handled

### ISSUE THREAD

**Issue by HiPhish** [p00f/nvim-ts-rainbow#109]
**Describe the bug**

If the file type of a buffer changes the parser of the initial language will still be used instead of instantiating a new parser.

**Steps to reproduce**

- Create a new buffer with a file type, e.g. `nvim derp.html`
- Change the file type, e.g. `set ft=lisp`

**Expected behavior**

The parentheses highlighting rules should match the new file type

We can use an auto command to watch for file type changes. The question is what to do with the old parser. Do we keep it around? Do we replace it? I would advocate for the latter, file types change very rarely, so there is no point in keeping an old parser around.

![Screenshot_20220417_115245](https://user-images.githubusercontent.com/4954650/163709666-ee78549c-93a7-4d6b-909a-315e33f4b52a.png)

**Comment by p00f** [comment]
Hmm parser.get_parser uses `lang`, which might not correspond to `filetype`
https://github.com/HiPhish/nvim-ts-rainbow/blob/1f6c2455b86221bfead1b01e431a43832b63b76a/lua/rainbow/internal.lua#L165

So how do we change the parser using an autocmd?

**Comment by p00f** [comment]
nvm there's `parsers.get_buf_lang(buf)`

**Comment by p00f** [comment]
check out https://github.com/p00f/nvim-ts-rainbow/tree/update_parser

**Comment by HiPhish** [comment]
When the parser is initially created in `M.attach` it uses whatever the `lang` argument is. I was not able to find documentation on what `lang` exactly is, so I am going to assume that it is whatever the file type of the buffer maps to in `'nvim-treesitter.parsers.get_buf_lang`. If `get_parsers` is called without `lang` argument the same happens.

**Comment by p00f** [comment]
distros haven't yet updated to 0.7, I need to rewrite the autocmd in vimscript 😭

**Comment by HiPhish** [comment]
> distros haven't yet updated to 0.7, I need to rewrite the autocmd in vimscript sob

Nah, just wrap it inside `if vim.fn.has('0.7') ~= 0`, eventually all distros will update to 0.7 and it's such a rare edge case no one has noticed yet, that it's not worth torturing yourself with Vim script.

**Comment by p00f** [comment]
nice, thanks!

**Comment by p00f** [comment]
I'm merging that branch now

**Comment by HiPhish** [comment]
Are you sure you want to have this autocommand for every buffer, even if it is not attached? You should be able to use `<buffer>` as the pattern, or `<buffer=N>` where `N` is the number of the current buffer. You would then need to create the auto command inside the `attach` function and remove it inside the `detach` function. I would like to try it, but Void Linux has not yet updated their package, so I would have to compile Neovim from source first.

**Comment by p00f** [comment]
https://github.com/p00f/nvim-ts-rainbow/blob/04284dc97eac0d0ecfea68e10be824d1a6585de0/lua/rainbow/internal.lua#L191-L205

changed it to check if it is attached

**Comment by p00f** [comment]
Is this fixed?

**Comment by p00f** [comment]
Yep

**Comment by HiPhish** [comment]
> Is this fixed?

Still not working with 0.7. It appears that the new parser is the exact same 
object as the old parser. Change the `if`-block in the callback:

```lua
        callback = function()
            local bufnr = api.nvim_get_current_buf()
            if state_table[bufnr] then
                local lang = parsers.get_buf_lang(bufnr)
                local old_parser = buffer_parsers[bufnr]
                local parser = parsers.get_parser(bufnr, lang)
                buffer_parsers[bufnr] = parser
                vim.cmd(string.format('echom "lol: %s, %d, %s, %s"', lang, 
bufnr, old_parser == parser, parser._lang))
            end
        end,
```

When I switch file types I get the output `lol: commonlisp, 1, true, html`. 
This means the language was detected properly, but Neovim is recycling parsers 
and ignoring the new language. This seems to be a Neovim bug, so there is 
nothing we can do for now.

**Comment by p00f** [comment]
as in, parsers.get_parser is returning the same object?

**Comment by HiPhish** [comment]
> as in, parsers.get_parser is returning the same object?

Even worse, Neovim's own `vim.treesitter.get_parser` is returning the same object. It does not update the language of the parser object. `parsers.get_parser` is just a wrapper around the Neovim function.

**Comment by HiPhish** [comment]
I have created a new issue: https://github.com/neovim/neovim/issues/18148. I'd say to leave this as it is for now, we have our code and when it's fixed in Neovim things should fall right in place.

**Comment by p00f** [comment]
👍🏽
