### ISSUE TITLE
Add support for solidity

### ISSUE THREAD

**Issue by alefbragin** [p00f/nvim-ts-rainbow#113]
Would love to have Solidity support, it's the language created to write Ethereum contracts.
The language is takes many syntactical ideas from JavaScript.

Currently it is supported by nvim-treesitter (https://github.com/nvim-treesitter/nvim-treesitter/issues/1168).

**Comment by p00f** [comment]
I don't use it so I can't test it, PRs welcome

**Comment by p00f** [comment]
closed by #114
