### ISSUE TITLE
tsx html element change color too

### ISSUE THREAD

**Issue by NoamMuallem** [p00f/nvim-ts-rainbow#119]
**Describe the bug**
in tsx files, all the html elements are colored like brackets

**Steps to reproduce**
install the plugin and add to treesitter.lua:
  rainbow = {
    enable = true,
    extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
    max_file_lines = nil, -- Do not enable for files with more than n lines, int
  }
 
**Expected behavior**
only brackets will be colored, not html elements, the html elements will inherit from color scheme...
 
you can see in the telescope preview of the file the correct colors for the html elements... 

**Screenshots**
![Screen Shot 2022-07-10 at 8 17 11](https://user-images.githubusercontent.com/40291455/178155884-5f04e8fc-d352-4e6e-b918-1f8627818a2b.png)
![Screen Shot 2022-07-10 at 8 17 35](https://user-images.githubusercontent.com/40291455/178155889-1845aac0-da60-47d1-842a-25e723419bae.png)

**Comment by p00f** [comment]
Turn off extended mode
