### ISSUE TITLE
Tsx colors are the other way around

### ISSUE THREAD

**Issue by Ryunaq** [p00f/nvim-ts-rainbow#123]
**Describe the bug**
Tsx colors are the other way around, tags are getting colored, while typescript type annotations are not.

**Steps to reproduce**
Enable rainbow without `extended_mode`.
```
  rainbow = {
    enable = true,
    extended_mode = false
  }
```

Example code:
```tsx
const Secret = () => {
  const test: Array<Array<number>> = [[]];

  return (
    <main>
      <div>
        <p>{test}</p>
      </div>
    </main>
  );
};

export default Secret;
```

**Expected behavior**
Same behavior as jsx files: jsx tags don't get colored, but with the addition of types annotations getting colored.

**Screenshots**
Tsx not working correctly
![image](https://user-images.githubusercontent.com/17756312/179050430-fb7cb6dd-950e-4221-b759-42147b515b33.png)

Jsx working fine
![image](https://user-images.githubusercontent.com/17756312/179050656-0fc3787c-aad4-4c25-b440-f1be8ef6c6ad.png)

**Comment by Ryunaq** [comment]
Arrays are working correctly now, tsx tags are not though

**Comment by p00f** [comment]
This one should be fixed but extended mode in jsx doesn't work for some reason

**Comment by Alex23rodriguez** [comment]
is there a branch where this issue is fixed? I just updated the package and tsx files are now messed up for me

![image](https://user-images.githubusercontent.com/22017085/182462404-c22f262b-9a32-4801-aeb6-18fba8418911.png)

**Comment by Gelio** [comment]
@Alex23rodriguez This should be fixed by https://github.com/p00f/nvim-ts-rainbow/pull/125
