### ISSUE TITLE
JSX is not highlighted in files with `jsx` extension

### ISSUE THREAD

**Issue by Gelio** [p00f/nvim-ts-rainbow#126]
While working on https://github.com/p00f/nvim-ts-rainbow/pull/125 I noticed that JSX elements are not highlighted in files with the `jsx` extension (`filetype=javascriptreact`).

**Steps to reproduce**

For a file `test.jsx`:

```jsx
import styles from "./App.module.css";

const App = () => {
  return (
    <div class={styles.App} data-comparison={1 < 2 && 1 > 2}>
      <header class={1 + 2 * (1 + 2) && styles.header}>
        <span>I should be highlighted</span>
      </header>
    </div>
  );
};

export default App;
```

with `extended_mode` enabled, the JSX tags are not highlighted by `nvim-ts-rainbow`. Parentheses are highlighted by `nvim-ts-rainbow` and have different colors.

![image](https://user-images.githubusercontent.com/889383/183247914-85ab5cdb-a7eb-4ddf-aaf6-ce433e1b6e0e.png)

**Expected behavior**

JSX tags are highlighted by `nvim-ts-rainbow`.

This works well for files with the `tsx` extension (see https://github.com/p00f/nvim-ts-rainbow/pull/125), but `jsx` extension is ignored.

Here is the expected look of this file (I did `:set filetype=typescriptreact` to achieve it):

![image](https://user-images.githubusercontent.com/889383/183247929-74bc60f4-748f-4758-a18f-6e7be862bbb7.png)

**Investigation**

I did some digging around and noticed that [the `parsername` for the `javascriptreact` filetype is `javascript`](https://github.com/nvim-treesitter/nvim-treesitter/blob/373b15ecee49f1604350e77fa7b93a1ef1e20baf/lua/nvim-treesitter/parsers.lua#L6-L8). For `tsx` and `typescriptreact`, [it is `tsx`](https://github.com/nvim-treesitter/nvim-treesitter/blob/373b15ecee49f1604350e77fa7b93a1ef1e20baf/lua/nvim-treesitter/parsers.lua#L11).

The jsx-highlighting queries [are defined for the `jsx` parser](https://github.com/p00f/nvim-ts-rainbow/blob/master/queries/jsx/parens.scm). It may be the case that the `jsx` parser is not used for the `jsx` files because it uses the `javascript` parser now.

Thus, I believe we should remove any code that references the `jsx` parser and instead add highlighting `jsx` to the `javascript` parser.

**Comment by p00f** [comment]
> Thus, I believe we should remove any code that references the jsx parser and instead add highlighting jsx to the javascript parser.

Can you do this? I'm not the best person to test this, someone who actually uses it can see all the edge cases.

Thanks!

**Comment by Gelio** [comment]
Sure, I'll see what I can do later today or tomorrow
