### ISSUE TITLE
Highlight `do` and `and` keywords for elixir

### ISSUE THREAD

**Issue by salfum** [p00f/nvim-ts-rainbow#129]
Many thanks for the development and support of the plugin. I tried to implement `do` and `end` keyword highlighting for the elixir programming language, but it didn't work for me. Could you suggest what I am doing wrong and how can I find a solution?

https://github.com/salfum/nvim-ts-rainbow/commit/7ead87dc818ce52b0a59f4d2f94446da90d95a38#diff-71e2cbc43e30cbee0bc7bf80ef1a9bc077ea2a724e92c853c8af3ed75823cdeb

https://github.com/salfum/nvim-ts-rainbow/commit/7ead87dc818ce52b0a59f4d2f94446da90d95a38#diff-cbd205d6e0165b8601e3c184b4fef1e527383bd9a428321c048ca1cbbdd50e7aR149-R161

**Comment by p00f** [comment]
Done, thanks - this is how to do it: https://github.com/p00f/nvim-ts-rainbow/commit/0c19f1eda263a1d44b6741e727fef223886c80a8
![image](https://user-images.githubusercontent.com/36493671/183562658-ac3998a6-99c7-4507-8d02-b73a5e9fb28f.png)

**Comment by p00f** [comment]
You can add the other ones like `->` similarly and make a PR

**Comment by p00f** [comment]
I reverted that commit but you can do the same in your personal fork
