### ISSUE TITLE
Rails string concat

### ISSUE THREAD

**Issue by crivotz** [p00f/nvim-ts-rainbow#13]
Hi, 
thanks for your plugins, work perfect with indent-blankline context features.

I have a problem with ruby (to be precise with ruby on rails), it's works perfect with all "brackets situation" except for this case

![bracket](https://user-images.githubusercontent.com/3275600/111912123-86ef6580-8a68-11eb-8efb-76335e6623f6.png)

Probably the format `#{ }` break the functionality.

**Comment by p00f** [comment]
Is it fine if the pound sign is not highlighted like 
![image](https://user-images.githubusercontent.com/36493671/111913345-b9628800-8a93-11eb-84d9-ec80c345b167.png)
If yes then 280d3241 should fix it

**Comment by crivotz** [comment]
That's fine. The opening is `#{` but it is also clear with the color change only the bracket.

Thanks

**Comment by p00f** [comment]
@crivotz  Can you try out f60193c ?
![image](https://user-images.githubusercontent.com/36493671/112106465-b79fde00-8bd3-11eb-9d81-901c0512e811.png)

**Comment by crivotz** [comment]
> @crivotz Can you try out [f61093c](https://github.com/p00f/nvim-ts-rainbow/commit/f61093c56a53c6790b142f76bdfaa476f497b93f) ?
> ![image](https://user-images.githubusercontent.com/36493671/112106465-b79fde00-8bd3-11eb-9d81-901c0512e811.png)

Perfect 👯
