### ISSUE TITLE
Add EJS?

### ISSUE THREAD

**Issue by rodhash** [p00f/nvim-ts-rainbow#139]
Hello,

Is it possible to add EJS chars for HTML lang? Like "<%" and "<%=" for opening and "%>" for closing. I tried myself but no luck there.

Thanks

**Comment by rodhash** [comment]
One more thing that would be nice is to not match ">" in the middle of the line.

Currently my "=>" for the callback fn became half highlighted:

![image](https://user-images.githubusercontent.com/29671981/192138105-af1a208e-cf7f-4745-b662-abbb40582e9a.png)

**Comment by p00f** [comment]
Can you paste an example

**Comment by rodhash** [comment]
Sorry delay..

Sure, in this example I'm updating the title:
```html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><%= pageTitle %></title>
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/forms.css">
    <link rel="stylesheet" href="/css/product.css">
</head>
```

Here, it's a full file (404.ejs) with 3 different includes:
```html
<%- include('./includes/head.ejs') %>

</head>
<%- include('./includes/navigation.ejs') %>

<body>
    <h1>Page Not Found!</h1>

<%- include('./includes/end.ejs') %>
```

Here, we have two variables `kindofday` and `el` and a array method being used `forEach`:
```html
<body>
    <h1><%= kindOfDay %> </h1>

    <ul>
        <% itemList.forEach( el => { %>
            <li><%= el %> </li>
        <% }) %>
    </ul>
</body>
```

**Comment by p00f** [comment]
tree-sitter doesn't recognise them:
![image](https://user-images.githubusercontent.com/36493671/192939858-f5b3bb3a-087b-40cd-ba7a-301fd532cc76.png)

**Comment by p00f** [comment]
nvim-treesitter needs to add the embedded_template language (no checkmark): https://github.com/nvim-treesitter/nvim-treesitter#supported-languages
