### ISSUE TITLE
Colorized bracket inside python f-strings

### ISSUE THREAD

**Issue by gabrielrojasc** [p00f/nvim-ts-rainbow#140]
**Describe the bug**

While using the plugin in python f-strings, brackets can be colorized the same color as the string color, so the brackets seem like not colorized.

**Steps to reproduce**

 - Use same string color in python as the first color for parenthesis/bracket.

```python
num = 10
s = f"Number: {num}"
```

For my colorscheme (peachpuff) and current ts-rainbow conf (default colors) it colorizes the string and the bracket the same color (red).

**Expected behavior**

```python
num = 10
s = f"Number: {num}"
```

In this code the bracket color inside the f-string should be a different color to the one used for strings.

**Screenshots**
With ts-rainbow on:
<img width="177" alt="Screen Shot 2022-09-25 at 19 28 35" src="https://user-images.githubusercontent.com/37199173/192168408-0c84f449-8a78-44d5-af17-a90330e7dc2e.png">

With ts-rainbow off:
<img width="178" alt="Screen Shot 2022-09-25 at 19 27 44" src="https://user-images.githubusercontent.com/37199173/192168377-fce576f1-bb57-4801-8af0-aba40409d4ff.png">

**Comment by p00f** [comment]
Can't really do anything, this is why you use different colours
