### ISSUE TITLE
Rainbow doesn't work in header file c

### ISSUE THREAD

**Issue by hungnguyen1503** [p00f/nvim-ts-rainbow#144]
**Describe the bug**
The rainbow works very well in file .c, but in the header file .h, I don't know why it doesn't work

My config:
local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
	return
end

---@diagnostic disable-next-line: redefined-local
local status_ok, install = pcall(require, "nvim-treesitter.install")
if not status_ok then
	return
end

configs.setup({
    ensure_installed = { "c", "cpp", "lua", "cmake", "python", "vim", "yaml", "json"}, -- one of "all" or a list of languages

    -- ensure_installed = {"maintained"}, -- one of "all" or a list of languages

    ignore_install = { "" }, -- List of parsers to ignore installing

    sync_install = true,

    auto_install = true,

    highlight = {
        enable = true, -- false will disable the whole extension
        use_languagetree = true,
        additional_vim_regex_highlighting = false,
    },
    autopairs = {
        enable = true
    },
    rainbow = {
        enable = true,
        extended_mode = true,
        max_file_lines = nil,
        colors = {
            '#458588',
            '#b16286',
            '#cc241d',
            '#d65d0e',
            '#458588',
            '#b16286',
            '#cc241d',
            '#d65d0e',
            '#458588',
            '#b16286',
            '#cc241d',
            '#d65d0e',
            '#458588',
            '#b16286',
            '#cc241d',
            '#d65d0e',
         },
         termcolors = {
            'brown',
            'Darkblue',
            'darkgray',
            'darkgreen',
            'darkcyan',
            'darkred',
            'darkmagenta',
            'brown',
            'gray',
            'black',
            'darkmagenta',
            'Darkblue',
            'darkgreen',
            'darkcyan',
            'darkred',
            'red',
         },
    },
	indent = { enable = true, disable = { "python", "css" } },
    matchup = {
        enable = true,
    }

})
install.compilers = {"x86_64-w64-mingw32-clang", "gcc", "g++"}

**Screenshots**
![image](https://user-images.githubusercontent.com/58872428/198360003-49fb4bd2-a2db-4e2b-8f35-f1599d5d124a.png)

**Comment by p00f** [comment]
You need to fill out the issue template fully

**Comment by hungnguyen1503** [comment]
Hi p00f, I have updated my config yet. Please check it.

**Comment by p00f** [comment]
You also need to paste the code which has buggy highlighting in addition to this screenshot

**Comment by p00f** [comment]
can this be closed?

**Comment by hungnguyen1503** [comment]
Ok, the tick can be close.
Many thanks
