### ISSUE TITLE
Enable for all files

### ISSUE THREAD

**Issue by Shatur95** [p00f/nvim-ts-rainbow#2]
Hi! Thank you a lot for the plugin!
I have a question. Can a plugin be enabled for languages ​​that Treesetter does not currently support? For example, for Vimscript.

**Comment by p00f** [comment]
Nope. But
1) vigoux is working on tree-sitter-vimscript !
2) luochen1990's rainbow plugin works very well (non-treesitter)
3) glepnir is working on rainbow _indents_ like visual studio

**Comment by Shatur95** [comment]
Thank you for the information!

**Comment by p00f** [comment]
Ye I mostly made this plugin because treesitter highlighting overrides the others, blocking other rainbow plugins in treesitter languages
