### ISSUE TITLE
Wrong colors after last update

### ISSUE THREAD

**Issue by argapost** [p00f/nvim-ts-rainbow#26]
Hello, 

I just updated using :PackerUpdate and the colors of  the function keyword in lua and parenthesis of functions became red.
Similar behaviour in python for some brackets and parenethesis.

Expected behaviour (before update):
![image](https://user-images.githubusercontent.com/58076098/114270720-37b8a700-9a0e-11eb-819f-23cbe5be4d4a.png)

Current behaviour:
![image](https://user-images.githubusercontent.com/58076098/114270769-74849e00-9a0e-11eb-94b0-665b4df66d06.png)

Thank you in advance.

**Comment by p00f** [comment]
https://github.com/p00f/nvim-ts-rainbow#setup

This is intended. Can you set `extended_mode ` to false and check?

**Comment by argapost** [comment]
Thank you for your reply.

This indeed fixed the colour of the 'function' and 'end' but in python still I see all brackets and parent red:
![image](https://user-images.githubusercontent.com/58076098/114272140-2de67200-9a15-11eb-9cf9-f5e048dc6355.png)

Whereas previously it was like that:
![image](https://user-images.githubusercontent.com/58076098/114272152-4060ab80-9a15-11eb-9957-3f7640adf42f.png)

Is this the expected behaviour?

**Comment by p00f** [comment]
Nope, this is a bug

@kil0meters

**Comment by p00f** [comment]
Is it fixed if you check out `445c02bb35e350df733af3ec70a0a7dea5dbcf43` ?

**Comment by argapost** [comment]
yes

**Comment by p00f** [comment]
Great. I'll unmerge that PR, download its patchset and reapply it (giving proper authorship to @kil0meters )after doing languagetree  (so that only changed nodes are processed ) because I think it degrades performance too.

**Comment by p00f** [comment]
Done

**Comment by argapost** [comment]
everything ok now. Thank you again!
