### ISSUE TITLE
Wrong colors in function definition in GDScript

### ISSUE THREAD

**Issue by Shatur95** [p00f/nvim-ts-rainbow#28]
Hi! I have the following highlighting issue:

![изображение](https://user-images.githubusercontent.com/22453358/115147420-91028500-a063-11eb-8fc6-573d7c3cdc6a.png)

Without this plugin:

![изображение](https://user-images.githubusercontent.com/22453358/115147447-abd4f980-a063-11eb-9736-28f4f97fdd37.png)

**Comment by p00f** [comment]
Can you check now? I don't know how I messed this up

**Comment by Shatur95** [comment]
> Can you check now? I don't know how I messed this up

Works, thanks!
