### ISSUE TITLE
Q: Shouldn't color depend on level of nesting, instead of order of appearance in buffer?

### ISSUE THREAD

**Issue by tstelzer** [p00f/nvim-ts-rainbow#34]
Note that this may be a duplicate of #33.

I believe the value in coloring parenthesis is in differentiating level of nesting, and should be identical between two sets of parenthesis. I want to be able to look at nested parenthesis and immediately identify the level of nesting of each parenthesis. That doesn't seem to be the case. But maybe I'm misunderstanding the point.

For the sake of argument, lets say we have three colors:

rainbowcol1 = gray
rainbowcol2 = red
rainbowcol3 = green

And three sets of parenthesis:

```
()
(())
((()))
```

I would **expect** them to be colored like this:

![image](https://user-images.githubusercontent.com/15860486/117533441-2488ff00-afed-11eb-88e7-e08217252fc7.png)

How they are **actually** colored is something like this:

![image](https://user-images.githubusercontent.com/15860486/117533592-f22bd180-afed-11eb-845c-e8518df734e2.png)

Is that a bug, or expected behavior?

**Comment by p00f** [comment]
What happens when you write something in the outer brackets?

It can be considered a bug (dup of #33)

**Comment by tstelzer** [comment]
By the way, here are two emacs plugins that behave the way I'm describing.

https://github.com/istib/rainbow-blocks
https://github.com/Fanael/rainbow-delimiters

So does this junegunn vim plugin:

https://github.com/junegunn/rainbow_parentheses.vim

**Comment by p00f** [comment]
> Here, I would expect both sets of inner parenthesis to be colored red.

Yes I understand

> Not sure if I understand the question. Do you mean, what happens if I add a set of parens on the same level as another set?

`(a + (b + (c +d)))`

Or something like this. What are the colours when you do this



I'm waiting for https://github.com/neovim/neovim/pull/14503 to be merged so I can merge the `incremental_updates` branch to `master` which would fix #5 . I don't want to do anything major until this is done because rebasing would be huge.

**Comment by tstelzer** [comment]
![image](https://user-images.githubusercontent.com/15860486/117542182-e228e780-b017-11eb-84c5-20aed5a54f8c.png)
