### ISSUE TITLE
Add support for Common Lisp

### ISSUE THREAD

**Issue by IanMejia** [p00f/nvim-ts-rainbow#35]
Support for Common Lisp was recently added to Treesitter, I have already added the current main parens to my clone of the repo, the only ones necessary are square brackets and parenthesis.

**Comment by p00f** [comment]
> I have already added the current main parens to my clone of the repo, 

Can you make a PR? you just need to fork this repo, add your fork as a remote to your clone, push to your fork and make a PR

**Comment by IanMejia** [comment]
Done. Thanks in advance for this awesome work. #36

**Comment by p00f** [comment]
Closed by #36
