### ISSUE TITLE
Updating with vim-plug is broken

### ISSUE THREAD

**Issue by carlocab** [p00f/nvim-ts-rainbow#40]
Doing `:PlugUpdate` with vim-plug has failed for me a couple of times recently, with the following error:
```
x nvim-ts-rainbow:
    fatal: Not possible to fast-forward, aborting.
```
When I check my local `nvim-ts-rainbow` repository, it seems that my copy is behind the GitHub repository by seven commits and ahead by three.

I don't make changes to my local repository, so I'm not sure how this happened. One possible explanation is that history in this repository gets rewritten with `git push --force`, which makes it impossible to update local remotes with a fast-forward only pull.

If this is what happened, could you please avoid this in the future to avoid breaking updates for your users? If this isn't what happened, it'd be useful to know what did so I can try to fix it. Thanks!

**Comment by p00f** [comment]
I'm so sorry, I forgot to switch branches and did WIP stuff on master, so I had to force push it back

**Comment by carlocab** [comment]
Please never force push to a branch that others are using. If you need to undo something, revert it properly.

**Comment by p00f** [comment]
Right, thanks!

**Comment by carlocab** [comment]
Thanks for your work on this plugin!
