### ISSUE TITLE
Reloading rainbow

### ISSUE THREAD

**Issue by ranjithshegde** [p00f/nvim-ts-rainbow#43]
## Expected behaviour:
 change colorscheme while vim is running.
 ts-rainbow still continues to work

## Actual behaviour:
 Change colorscheme while nvim running.
 rainbow no more. The colors of parenthesis are back to vanilla Treesitter

## Steps to reproduce
 1. Change colorscheme (or in some cases change background to light) when vim is running
 2. Same error on resourcing vimrc

**Comment by p00f** [comment]
Do you change your colorscheme inside vim frequently? (PS: I'm not saying this is not a valid issue)

**Comment by ranjithshegde** [comment]
Well not exactly colorscheme. But yes i do change from light to dark background fairly frequently.

**Comment by p00f** [comment]
Should be fixed now
