### ISSUE TITLE
I have no idea how to install this plugin

### ISSUE THREAD

**Issue by oryband** [p00f/nvim-ts-rainbow#49]
Can you please provide instructions in the readme on how to install this plugin with `:TSInstall` ?

**Comment by p00f** [comment]
`:TSInstall` is for installing parsers ...

Install this like any other plugin, then do [this](https://github.com/p00f/nvim-ts-rainbow#setup) in lua or wrap it in
```
lua << EOF
<config_here>
>> EOF
```

**Comment by oryband** [comment]
Won't hurt to mention this in the README.
