### ISSUE TITLE
Doesn't work well with twilight.nvim

### ISSUE THREAD

**Issue by mTvare6** [p00f/nvim-ts-rainbow#50]
![image](https://user-images.githubusercontent.com/57838468/125611062-77c01932-7112-4a28-92ef-9545dcd08db5.png)

**Comment by p00f** [comment]
There's nothing I can do without a _lot_ of work, just disable rainbow in that buffer if you want `:TSBufDisable rainbow1

**Comment by p00f** [comment]
This would require me to reimplement quite a lot of twilight

**Comment by mTvare6** [comment]
I don't use twilight much anyways, just felt like reporting if anyone hadn't
