### ISSUE TITLE
Add support for custom delimeters?

### ISSUE THREAD

**Issue by DukMastaaa** [p00f/nvim-ts-rainbow#51]
I would like to suggest a feature to add support for specifying custom left and right delimeters, for example `\left(` and `\right)` pairs in LaTeX. It seems like `\(` and `\)` have already been implemented.

**Comment by p00f** [comment]
`\left` and `\right` are there, but broken
https://github.com/p00f/nvim-ts-rainbow/blob/15e8a45517c596b9acd9406bcb6f650d6bfdb339/queries/latex/parens.scm#L6-L15

For custom queries can you try https://github.com/nvim-treesitter/nvim-treesitter#adding-queries ?

**Comment by p00f** [comment]
Wait it works
![image](https://user-images.githubusercontent.com/36493671/125890256-db2c94e5-ba1b-4212-97ad-43ebc0f28cf4.png)

**Comment by p00f** [comment]
Did you enable extended mode in your config?

**Comment by p00f** [comment]
Closing as `\begin` and `\end` already work
