### ISSUE TITLE
Rewriting the history on public master breaks updating the plugin for packer

### ISSUE THREAD

**Issue by lockejan** [p00f/nvim-ts-rainbow#52]
Hey,
every time the history is rewritten on master it breaks updating the plugin with packer.
IMO such a workflow on public branches isn't a good practice and should be avoided in general, but that's up to the maintainer(s).

There is also an open issue on packer that explains a bit more:
https://github.com/wbthomason/packer.nvim/issues/327

Maybe the current workflow can be reconsidered as I really appreciate the plugin.

**Comment by p00f** [comment]
I haven't done any force pushes recently

**Comment by p00f** [comment]
I've done this earlier too (#40 ), I promise I'll never do this again

**Comment by lockejan** [comment]
Haha, I've noticed it the last time as well but I hoped it would be just an exception. 
I've ran into situations where it was necessary to rebase (e.g. accidentally committing sensitive information).

Anyway thanks for your response. Keep up the good work.

**Comment by p00f** [comment]
I have now set a branch protection rule for master which disallows force pushes

**Comment by carlocab** [comment]
This broke my update too; I was just about to come here to mention this again. Branch protection on master is a good idea; I should've mentioned this last time. Thanks again!
