### ISSUE TITLE
Git Issues (with Packer)

### ISSUE THREAD

**Issue by SethGower** [p00f/nvim-ts-rainbow#54]
Hello,
I am using this plugin (absolutely love it), and installed with [Packer](https://github.com/wbthomason/packer.nvim). A couple times in the past week I have gotten issues with this plugin while updating (via `:PackerSync`) with git saying `fatal: refusing to merge unrelated histories`. I tried going into the git directory directly, and get the same thing when I run `git pull`. Do you have any idea why this would be happening? Is this an issue in Packer, have there been force pushes here or something? This is the only plugin showing this behavior

**Comment by p00f** [comment]
There have been force pushes (there won't be any more, master now has a branch protection rule). Sorry about this!

**Comment by SethGower** [comment]
Ok, thanks. I had a feeling that's what caused that. I just wanted to make sure before I went and made an issue on Packer.
