### ISSUE TITLE
This plugin completely messes up my colourscheme

### ISSUE THREAD

**Issue by TarunDaCoder** [p00f/nvim-ts-rainbow#55]
Hello, I installed this plugin, and its a very fun and helpful one, but it seems to mess up my colour scheme when I add the boilerplate code for HTML, here's a screenshot
![image](https://user-images.githubusercontent.com/77536695/126734770-c71436b6-8fbf-4d3d-b493-c6815f91e19c.png)

and here is my config for rainbow
```lua
rainbow = {
    	enable = true,
    	extended_mode = true, -- Highlight also non-parentheses delimiters, boolean or table: lang -> boolean
    	max_file_lines = 1000, -- Do not enable for files with more than 1000 lines, int
    	colors = {
			"#ff003c",
			"#ca0bd4",
			"#e973f0",
			"#710578",
			"#780527",
			"#a600ff",
			"#eb445d"
		} -- table of hex strings
  	}
```
and I'm using this colour scheme btw https://github.com/monsonjeremy/onedark.nvim
Thanks

**Comment by p00f** [comment]
This is intended for extended mode
without extended mode:
![image](https://user-images.githubusercontent.com/36493671/126736600-279df6e1-fcc3-4880-8fc1-c699abb1c326.png)

with extended mode:
![image](https://user-images.githubusercontent.com/36493671/126736560-e698d6da-49dd-4ba7-aa90-3eb7856aeac0.png)

**Comment by p00f** [comment]
Oh it's still buggy because the levels are still in the query file so the tags are still coloured differently

**Comment by p00f** [comment]
Fixed

**Comment by TarunDaCoder** [comment]
Thanks
