### ISSUE TITLE
Add `Scala` programming lang support

### ISSUE THREAD

**Issue by softinio** [p00f/nvim-ts-rainbow#56]
Hi 

Using this awesome plugin for the first time with Scala project, this one: [scala project](https://github.com/lrodero/cats-effect-tutorial/tree/series/3.x)

It doesn't seem to work. 

Here is my neovim [init.lua](https://github.com/softinio/nix-config/blob/main/programs/neovim/init.lua) in case useful to see if I am doing something wrong in my setup.

here is a screenshot: 

![screenshot](https://shared.softinio.com/Screen-Shot-2021-07-31-08-52-35.58.png#31cbd94595387d1ff74e13ace5b24bbc950bb2d39445d6742c49dce1baf9a03a)

**Comment by p00f** [comment]
Does scala have delimiters other than `{...}` `(...)` and `[...]`?

**Comment by softinio** [comment]
> Does scala have delimiters other than `{...}` `(...)` and `[...]`?

those are the main ones, unless you want to include quotes `' '` and double quote `" "`

**Comment by softinio** [comment]
@p00f thank you. All working now.
