### ISSUE TITLE
No rainbow on Terraform/HCL files.

### ISSUE THREAD

**Issue by stevenproctor** [p00f/nvim-ts-rainbow#59]
I have `extended_mode` configured as `true`, but do not see any rainbow parens set on my `.tf` files, and I have `hcl` installed for TreeSitter.

When I open up Fennel and Clojure files I see the pretty rainbow, but not when in Terraform files.

Are there any other things that I should check on settings to help give feedback on why they are not showing.

Thanks!

**Comment by ram02z** [comment]
@stevenproctor It seems like neither hcl or terraform have queries in this repository. You should create a PR adding the two query files. (See the fennel queries for reference).

**Comment by p00f** [comment]
Fixed by #60
