### ISSUE TITLE
Ocaml queries breaks `TSModuleInfo`

### ISSUE THREAD

**Issue by ram02z** [p00f/nvim-ts-rainbow#63]
**Steps to reproduce**
1. Run `TSModuleInfo` after nvim-ts-rainbow has been loaded
2. Presented with the following error:
` E5018: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 142`

**Expected behavior**
`TSModuleInfo` shouldn't throw an error.

**Notes**
After playing with the respective `paren.scm` file, turns out the the following line is causing the issue:
https://github.com/p00f/nvim-ts-rainbow/blob/68afca45319e155e9b948163192182e6649562fb/queries/ocaml/parens.scm#L5

You can try removing that query and the error can't be reproduced anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/59267627/130483884-ad03fd15-e6ad-4cbd-86d7-4b75b01f7905.png)

**Comment by p00f** [comment]
Sorry for taking so long!
