### ISSUE TITLE
Parentheses aren't colored for Fennel

### ISSUE THREAD

**Issue by katawful** [p00f/nvim-ts-rainbow#67]
**Describe the bug**
For fennel, parentheses are not colored. They maintain the default syntax color

**Steps to reproduce**
Install Fennel parser with nvim-treesitter along with this plugin with the default settings

**Expected behavior**
Parentheses should be colored like brackets and curly brackets, they are not

**Screenshots**
![2021-09-22~13:27:26](https://user-images.githubusercontent.com/45222045/134392319-fa01c08c-5207-433d-bf35-0bfa2602366b.png)

**Comment by p00f** [comment]
the fennel parser was updated recently, i'll update my queries soon. For now you can comment out https://github.com/p00f/nvim-ts-rainbow/blob/2f39c594a8d110bd4fcb75288a7d03cb93c81ea2/lua/rainbow/levels.lua#L60-L77

**Comment by katawful** [comment]
Awesome, thanks!

**Comment by p00f** [comment]
Should be fixed now, I tested this on all I could think of. Let me know if you find consecutive brackets with the same colour

**Comment by katawful** [comment]
It indeed works, thanks again!
