### ISSUE TITLE
[bug] error loading rainbow module from treesitter

### ISSUE THREAD

**Issue by alexzanderr** [p00f/nvim-ts-rainbow#69]
this error occurs after manually loading using `TSBufEnable rainbow`
```
E5108: Error executing lua ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:
424: loop or previous error loading module 'rainbow.internal'
```
because by default it doesnt load properly.

my TS config:
```lua
require"nvim-treesitter.configs".setup {
    autopairs = { enable = true },
    ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
    ignore_install = {}, -- List of parsers to ignore installing
    highlight = {
        enable = true, -- false will disable the whole extension
        -- disable = { "c", "rust" },  -- list of language that will be disabled
        -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
        -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
        -- Using this option may slow down your editor, and you may see some duplicate highlights.
        -- Instead of true it can also be a list of languages
        additional_vim_regex_highlighting = false
    },
    incremental_selection = {
        enable = false,
        keymaps = {
            init_selection = "gnn",
            node_incremental = "grn",
            scope_incremental = "grc",
            node_decremental = "grm"
        }
    },
    indent = { enable = true },
    autotag = {
        enable = true,
        filetypes = {
            "html",
            "javascript",
            "javascriptreact",
            "typescriptreact",
            "svelte",
            "vue",
            "xml"
        }
    },
    rainbow = {
        enable = true,
        extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
        max_file_lines = nil, -- Do not enable for files with more than n lines, int
        colors = {
            "#cc241d",
            "#a89984",
            "#b16286",
            "#d79921",
            "#689d6a",
            "#d65d0e",
            "#458588"
        }, -- table of hex strings
        termcolors = {
			"red",
			"yellow"
		} -- table of colour name strings
    }
    -- nvimGPS = {
    -- 	enable = true
    -- }
}

all parses are installed. so its not a problem with parsers.
```

plugin is installed using packer
```lua
	use { "p00f/nvim-ts-rainbow" }
```

when opening neovim i dont get any errors, but rainbow doesnt work because brackets are not colored. maybe because treesitter failed to load it and decided to not tell me anything about it.

after loading module manually it throws error.

is there a `setup` function for this plugin, to load it manually?

how do i fix the bug?

**Comment by alexzanderr** [comment]
i have neovim 0.6 and many other plugins. everything is installed and ensured.

**Comment by p00f** [comment]
Can you send the file in which it throws the error?

**Comment by gjeusel** [comment]
Had the same, having a look at the sources, there is a restriction: you have to have the same number of colors defined in `colors` and in `termcolors`.

**Comment by p00f** [comment]
Yes, `termcolors` cannot be less than `colors` because we iterate through `1..#colors`. If `termcolors` has more elements than `colors` then the extra ones do nothing

**Comment by p00f** [comment]
> Yes, `termcolors` cannot be less than `colors` because we iterate through `1..#colors`. If `termcolors` has more elements than `colors` then the extra ones do nothing

I don't think there is a solution to this, if you wish to have only 2 termcolors then repeat them till `#termcolors == #colors`, like 
```lua
termcolors = {
    "red",
    "yellow",
    "red",
    "yellow",
    "red",
    "yellow",
}
```

In this case you have to have an even number of colours in `colors`

**Comment by alexzanderr** [comment]
> Had the same, having a look at the sources, there is a restriction: you have to have the same number of colors defined in `colors` and in `termcolors`.

how about just having `termcolors` commented?

**Comment by p00f** [comment]
Should be fine in your case

**Comment by alexzanderr** [comment]
okey, i saw that having this config 
```lua
        colors = {
            "#cc241d",
            "#a89984",
            "#b16286",
            "#d79921",
            "#689d6a",
            "#d65d0e",
            "#458588"
        }, -- table of hex strings
        -- termcolors = { "red", "yellow" } -- table of colour name strings
```
works. but only if i manually enable rainbow with `:TSBufEnable rainbow`

**Comment by p00f** [comment]
Which filetype? Can you send the file

**Comment by alexzanderr** [comment]
python. its a huge 1000 lines. doesnt matter the contents of the file. its just python

**Comment by alexzanderr** [comment]
with rainbow config that is fine after entering in file
![image](https://user-images.githubusercontent.com/54772464/135498174-15e0dc27-b41e-4eb7-842b-92bc429d686d.png)

after manually enabling rainbow
![image](https://user-images.githubusercontent.com/54772464/135498216-9b21224e-e48e-4a4a-9350-115c9a32de16.png)

**Comment by alexzanderr** [comment]
i guess its tree sitter's fault, because of the other problems that im experiencing (indent, highlighting)
