### ISSUE TITLE
[Documentation] Needs help - plugin configuration problems

### ISSUE THREAD

**Issue by optimizasean** [p00f/nvim-ts-rainbow#71]
Where it is stated in the documentation to use the require statement after installing, it is not clear why it won't work to new users (new nvim user here, formerly a well established vim user trying to switch 😆 ).

I would like to add a clarity note that after the plugin is installed, specifically with vim-plug that the require statement must be made after `plug#end`.

I also did not know I needed to pipe it through `lua <<EOF <code goes here> EOF` for it to accept it.

Maybe provide this as a sample:
```vim
" Example using vim-plug to install the plugins

" Start installing plugins using vim-plug
call plug#begin('~/.config/nvim/plugins')

" Install plugins
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'p00f/nvim-ts-rainbow'

" Finish installing plugins with vim-plug
call plug#end()

" Configure nvim-treesitter
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  -- ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true,              -- false will disable the whole extension
    -- disable = {},  -- list of language that will be disabled
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
EOF

" Configure nvim-ts-rainbow
lua <<EOF
require'nvim-treesitter.configs'.setup {
  rainbow = {
    enable = true,
    extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
    max_file_lines = nil, -- Do not enable for files with more than n lines, int
    -- colors = {}, -- table of hex strings
    -- termcolors = {} -- table of colour name strings
  }
}
EOF
```

Treesitter must also be configured before this plugin is configured or it will not work.

It should also be noted that this plugin will not work unless treesitter has the linter for the language of the file that is open, therefore if treesitter does not contain the language, then this plugin will not work on that type of file.

The code above only configures it to work for the languages in treesitter that are listed as maintained, for full coverage by all languages in treesitter, set `maintained` to `all`.

Thoughts on the documentation updates?

**Comment by optimizasean** [comment]
So I did get it working (mostly) - it works on all languages recognized by treesitter.  However the file has to be opened with an extension recognized so the language is parsed properly.  I thought it might be just matching parenthesis through basic expression tree building although this one is a lot more complicated (and better :D).

**Comment by optimizasean** [comment]
@p00f looks much clearer now.  The link helps for those who click it 😆 !

For `Install this plugin, then add a rainbow section in the call to require("nvim-treesitter.configs").setup():`

Maybe semantics here but *Where is the require call found?*.  Could add in that treesitter must be set up according to the documentation (linked) and then add the call to the config in the treesitter setup?

^ For that, I actually didn't realize I could add the rainbow config with the treesitter config all in the same block like:
```vim
" Example using vim-plug to install the plugins

" Start installing plugins using vim-plug
call plug#begin('~/.config/nvim/plugins')

" Install plugins
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'p00f/nvim-ts-rainbow'

" Finish installing plugins with vim-plug
call plug#end()

" Configure nvim-treesitter and nvim-ts-rainbow combined
lua <<EOF
require'nvim-treesitter.configs'.setup {
  -- TREESITTER CONFIGS BEGIN
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  -- ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true,              -- false will disable the whole extension
    -- disable = {},  -- list of language that will be disabled
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
  -- TREESITTER CONFIGS END
  -- RAINBOW CONFIGS BEGIN
  rainbow = {
    enable = true,
    extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
    max_file_lines = nil, -- Do not enable for files with more than n lines, int
    -- colors = {}, -- table of hex strings
    -- termcolors = {} -- table of colour name strings
  }
  -- RAINBOW CONFIGS END
}
EOF
```

Also not the most familiar with Lua beyond basic pandoc parsers so I hope the combined above is still good 😆

**Comment by p00f** [comment]
Does it look fine now?
> . The link helps for those who click it
> Where is the require call found?.

I don't know how to put it concisely without the link :confused:

**Comment by optimizasean** [comment]
I think so, much better!  Sorry for the delay, got lost in the matrix 😁

**Comment by optimizasean** [comment]
Yeah, we can definitely mark it as closed, the README very clearly shows how to add configuration!

Thanks!
