### ISSUE TITLE
C++ Function {}  becomes gray with Neoformat clang-format

### ISSUE THREAD

**Issue by HATTER-LONG** [p00f/nvim-ts-rainbow#75]
C++ Function {}  becomes gray with Neoformat clang-format

-------------------

1. change some {} position:
![image](https://user-images.githubusercontent.com/31438141/140603019-4de5b703-f710-4338-aeef-79ff66f9756c.png)
2. use Neoformat cmd:
![image](https://user-images.githubusercontent.com/31438141/140603046-83ef3368-e145-4607-a99c-904db88beeef.png)
--------------------

nvim: 0.6
rainbow:lastest

myconfig:

```lua
rainbow = {
    enable = true,
    extended_mode = true, -- Highlight also non-parentheses delimiters, boolean or table: lang -> boolean
    max_file_lines = 1000 -- Do not enable for files with more than 1000 lines, int
},
-- packer
editor['p00f/nvim-ts-rainbow'] = {
    opt = true,
    after = 'nvim-treesitter',
    event = 'BufRead'
}
```
----------------------

How should I fix this?

**Comment by p00f** [comment]
Does this still happen? I can't reproduce this

**Comment by HATTER-LONG** [comment]
thanks replay.
I used efm to replace neoformat. so it's not happen now. I think it's some error for old version neoforamt, maybe i can close this issus.
