### ISSUE TITLE
Disable for tags, inside of jsx, tsx

### ISSUE THREAD

**Issue by ChristianChiarulli** [p00f/nvim-ts-rainbow#78]
Not sure if there is an option but I would like to disable for html, and jsx tags.   

![image](https://user-images.githubusercontent.com/29136904/141060691-56d19191-238d-4579-af81-aee9f4302135.png)

**Comment by ChristianChiarulli** [comment]
Sorted it out like this:

```local enabled_list = { "javascriptreact", "typescriptreact" }
local parsers = require "nvim-treesitter.parsers"
lvim.builtin.treesitter.rainbow = {
  enable = true,
  colors = {
    "Orchid",
    "Gold",
    "DodgerBlue",
    -- "Cornsilk",
    -- "Salmon",
    -- "LawnGreen",
  },
  -- Enable only for lisp like languages
  disable = vim.tbl_filter(function(p)
    local disable = true
    for _, lang in pairs(enabled_list) do
      if p == lang then
        disable = false
      end
    end
    return disable
  end, parsers.available_parsers()),
}
```

**Comment by p00f** [comment]
Nope this is not possible

**Comment by ChristianChiarulli** [comment]
You couldn't find a way to ignore jsx elements?

![image](https://user-images.githubusercontent.com/29136904/141063506-fa175107-151a-4012-b433-b65436be4b00.png)

**Comment by ChristianChiarulli** [comment]
I disabled them by just removing the jsx query:

![image](https://user-images.githubusercontent.com/29136904/141064016-05fd9570-60c4-47b3-b8a7-3c13b6b207a4.png)

I think this is preferable.

**Comment by ChristianChiarulli** [comment]
So couldn't we ignore `jsx` right here:

```    require("nvim-treesitter").define_modules({
        rainbow = {
            module_path = "rainbow.internal",
            is_supported = function(lang)
                return queries.get_query(lang, "parens") ~= nil
            end,
            extended_mode = true,
        },
    })
```

**Comment by p00f** [comment]
You could ignore jsx entirely yeah, not just tags tho

**Comment by p00f** [comment]
To disable jsx you can just add jsx to the `disabled` list during setup

**Comment by ChristianChiarulli** [comment]
Gotcha, well I'm not sure if it's possible outside of removing the jsx file from queries, I would argue you should remove it, since jsx tags aren't really hard to tell apart. It also is a little too noisy imo.

**Comment by ChristianChiarulli** [comment]
> To disable jsx you can just add jsx to the `disabled` list during setup

but that would disable everything unfortunately.

**Comment by p00f** [comment]
> Gotcha, well I'm not sure if it's possible outside of removing the jsx file from queries

You can just add jsx to `disabled = {...}` here https://github.com/p00f/nvim-ts-rainbow/blob/master/README.md#installation-and-setup

**Comment by p00f** [comment]
I don't really use jsx to have an opinion on tags

**Comment by ChristianChiarulli** [comment]
maybe we can just leave this open and see if there is any support, or maybe take a poll somewhere. If not I'm ok with my fork for now.

**Comment by mmirus** [comment]
I'm also trying to disable coloring the `<>` characters on tags in JSX. From the README, I thought this would be handled by the `extended_mode` option:

```
    extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
```

 but setting that to false doesn't make any noticeable difference.

**Comment by p00f** [comment]
setting that to true will also highlight the text inside tags

**Comment by mmirus** [comment]
Gotcha. Thanks for clarifying!

**Comment by p00f** [comment]
Fixed

**Comment by mmirus** [comment]
Thank you!
