### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Rofer11607** [p00f/nvim-ts-rainbow#82]
**Describe the bug**
There are no colors for matching brackets

**Steps to reproduce**
Install tree sitter, 
(via vim plug) install p00f/nvim-ts-rainbow
open a jsx file.
```lua
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = "maintained",
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = true,
    },
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "<leader>so",
            node_incremental = "<leader>",
            scope_incremental = "grc",
            node_decremental = "grm",
        },
    autotag = {
        enable = true,
    },
    rainbow = {
    enable = true,
    termcolors = {
          "#E06C75",
          "#E5C07B",
          "#98C379",
          "#56B6C2",
          "#61AFEF",
          "#C678DD",
          "#E06C75"
        },
      colors = {
            "#E06C75",
            "#E5C07B",
            "#98C379",
            "#56B6C2",
            "#61AFEF",
            "#C678DD",
            "#E06C75"
          },
      extended_mode = true,
      max_file_lines = 1000,
    },
    indent = {
      enable = true
    },
    }
}
EOF
```
**extra info:
:lua print(vim.inspect(colors)) 
Returns ~~null~~ nil

**Expected behavior**
Brackets should be colored.

**Screenshots**
<img width="643" alt="image" src="https://user-images.githubusercontent.com/55964540/147000481-a3607acc-1157-4d8a-862a-2bb659c14fe2.png">

**Comment by p00f** [comment]
can you post the jsx code?

**Comment by p00f** [comment]
you have defined rainbow inside incremental selection

**Comment by p00f** [comment]
>**extra info:
>:lua print(vim.inspect(colors))
>Returns null nil

`colors` is a local variable, so it won't be defined everywhere

**Comment by Rofer11607** [comment]
lol I guess that's why I need colored brackets. Sorry to bother you with such a dumb mistake.
