### ISSUE TITLE
Python () and [] not colouring

### ISSUE THREAD

**Issue by KarimLeVallois** [p00f/nvim-ts-rainbow#85]
**Describe the bug**
Python () and [] not colouring, but {} works fine, along with other file types.

**Steps to reproduce**
```
local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
  return
end

configs.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  sync_install = false, -- install languages synchronously (only applied to `ensure_installed`)
  ignore_install = { "" }, -- List of parsers to ignore installing
  autopairs = {
    enable = true,
  },
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { "" }, -- list of language that will be disabled
    additional_vim_regex_highlighting = true,
  },
  indent = { enable = true, disable = { "yaml" } },
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  },
  rainbow = {
  enable = true,
  extended_mode = true, -- Highlight also non-parentheses delimiters, boolean or table: lang -> boolean
  max_file_lines = 2000, -- Do not enable for files with more than 2000 lines, int
  colors = {
    "#81A1C1",
    "#A3BE8C",
    "#B48EAD",
    "#F0D399",
    "#D9B263",
    "#A6ACB9",
  }, -- table of hex strings
  -- termcolors = {} -- table of colour name strings
  },
  autotag = { enable = true },
}

```

**Expected behavior**
() and [] should colour as requested in the config.

[treesitter.txt](https://github.com/p00f/nvim-ts-rainbow/files/7892462/treesitter.txt)

**Comment by p00f** [comment]
It works for me, paste a python snippet for which it doesn't work

**Comment by KarimLeVallois** [comment]
It doesn't work for any Python file I am using and I even had someone on the LunarVim 'Neovim' channel personally use my config and they were getting the same issue with their Python files too. So different Neovim instance completely, different Python files, just the same Treesitter config I provided to you.

**Comment by KarimLeVallois** [comment]
I'm running Neovim 0.6.1 if that helps?

**Comment by p00f** [comment]
I just tried it on https://github.com/kovidgoyal/kitty/blob/master/kitty/rc/set_background_image.py on both neovim 0.6.1 and 0.7 (at https://github.com/neovim/neovim/commit/96aa7dd09779d2f0c52cb4fbe5cc785331a7fbd0), it works :/

**Comment by KarimLeVallois** [comment]
Very strange :/ Do you want me to provide my Neovim config to take a look at? I'm using it on iTerm2, macOS 12.1.

**Comment by p00f** [comment]
Can you update and try again?

**Comment by KarimLeVallois** [comment]
Just updated via :PackerSync, but same issue applies. All the () are reddish for example, not theming as expected.

**Comment by KarimLeVallois** [comment]
[nvim.zip](https://github.com/p00f/nvim-ts-rainbow/files/7920254/nvim.zip)

Here's my full config.

**Comment by p00f** [comment]
I can't go through that, I need a minimal config to reproduce

**Comment by KarimLeVallois** [comment]
Sorry, thought you would know where to look rather than having to go through the whole thing.

**Comment by p00f** [comment]
Your treesitter config seems fine but I can't reproduce the issue

**Comment by KarimLeVallois** [comment]
It's strange another person had the same issue. Will have to try and troubleshoot myself then.

**Comment by KarimLeVallois** [comment]
OK, some weirdness going on. If I create a new Python file or amend a Python file I can see the colours, but if I open a Python file just as is the brackets are all red and not coloured.

**Comment by KarimLeVallois** [comment]
[ex_10.txt](https://github.com/p00f/nvim-ts-rainbow/files/7920455/ex_10.txt)

Example .py file, just need extension changed back from .txt

**Comment by p00f** [comment]
![image](https://user-images.githubusercontent.com/36493671/150678205-c2a53f8e-0f69-41ef-a039-40d76750001a.png)

**Comment by p00f** [comment]
![image](https://user-images.githubusercontent.com/36493671/150678217-272313f9-1feb-48a4-8cd2-ef6cd5b6f819.png)

**Comment by KarimLeVallois** [comment]
It does the same on yours too then, only red coloured. If you edit the file and add ((((((())))))), {{{{{{{}}}}}}} and [[[[[[[]]]]]]] you should see those colour fine on the exact same file?

**Comment by p00f** [comment]
Brackets at the same level are supposed to be the same colour.....
Note that the square bracket around the cursor is brown

In any case
![image](https://user-images.githubusercontent.com/36493671/150678635-655d8b12-367b-47fe-9a31-f993818b34a5.png)

**Comment by KarimLeVallois** [comment]
I haven't got red in my Treesitter config though. Maybe try my config and you'll see they're still red in the file.

**Comment by p00f** [comment]
I can't reproduce this, feel free to reopen this if you can do so with a minimal config
