### ISSUE TITLE
Using vim.highlight.range with priority of 100 causes weird behavior

### ISSUE THREAD

**Issue by harrygallagher4** [p00f/nvim-ts-rainbow#87]
**Describe the bug**
Since d1251a1da38c3eabf7dcc796b7ca567530ac5e99 highlighting has been acting weird. All types of brackets/parens switch between their default color (`TSPunctBracket`) and their assigned rainbow color as the cursor moves around. This can easily be fixed by increasing the priority. I think using a higher priority than `nvim-treesitter` highlighting makes perfect sense anyway. I would consider the `nvim-treesitter` color the "default" which I would expect to see without this plugin, thus this plugin's highlighting takes priority.

**Steps to reproduce**
Open any file with brackets and move the cursor around

**Expected behavior**
Brackets should not revert to their default highlight color

**Screenshots**
This is what happens with priority 100 (now). Setting priority to 101 or greater fixes it.

https://user-images.githubusercontent.com/1610434/150295392-5bcf2ba3-0d98-4982-b30f-1ae7438b2cb1.mp4

**Comment by p00f** [comment]
I've set it to 120 now, lightspoeed.nvim uses 150 and this should be lower
