### ISSUE TITLE
TSX/typescriptreact not updating properly

### ISSUE THREAD

**Issue by Quaqqer** [p00f/nvim-ts-rainbow#89]
**Describe the bug**
The parenthesis seems to not get updated correctly in tsx, but it seems to work correctly in jsx. It does work if you turn rainbow off and on, but it does not update while typing.

**Steps to reproduce**
```tsx
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```
No parenthesis are updated, above is a code example.

I simpy try to put in some parenthesis and they don't get highlighted. For instance: `(() => {})()`.

**Expected behavior**
I expect the parenthesis to be updated with colors when I type.

**Screenshots**
Actual:
![2022-01-27-184106_954x520_scrot](https://user-images.githubusercontent.com/29512047/151414045-41396117-1ffe-4208-806e-00e3028cdfb2.png)

Expected:
![2022-01-27-184143_954x520_scrot](https://user-images.githubusercontent.com/29512047/151414088-d5ab72a7-f101-4fa4-80b2-ffc441c86957.png)

**Comment by p00f** [comment]
Are you using the latest version? I cannot reproduce this

**Comment by Quaqqer** [comment]
It took some debugging to find the culprit, it was [vim-doge](https://github.com/kkoomen/vim-doge). Unfortunate, because I quite liked that plugin. No idea what causes this. I guess you can close this issue.

**Comment by p00f** [comment]
I think doge downloads its own tree-sitter. You can try out danymat/neogen

**Comment by Quaqqer** [comment]
Neogen is exactly what I've been looking for, thanks man. <3
