### ISSUE TITLE
Calling command `edit` on the file cause error

### ISSUE THREAD

**Issue by tigorlazuardi** [p00f/nvim-ts-rainbow#95]
I get the issue when updating to commit [35bef9212441ef3f4b69c8ead0fbde123357bb4d](https://github.com/p00f/nvim-ts-rainbow/commit/35bef9212441ef3f4b69c8ead0fbde123357bb4d).

How I get this error:

1. go to normal mode.
2. type `:edit<cr>` . essentially like reopening the current file/buffer.

![image](https://user-images.githubusercontent.com/49936087/155530896-c8a2d53c-69bc-480f-ae37-b72c8eb80eaa.png)

Returning to [previous commit](https://github.com/p00f/nvim-ts-rainbow/commit/7e1af3e61b8f529031b54369fd54936c2a288e1b), resolved this issue.

This happens in Lua file, and not in Markdown file. Not tested in other filetypes though.

**Comment by p00f** [comment]
If you use neovim nightly then you need to update

**Comment by tigorlazuardi** [comment]
Thx. Updating neovim fixed the issue.
