### ISSUE TITLE
Add scheme language support 

### ISSUE THREAD

**Issue by fraschm1998** [p00f/nvim-ts-rainbow#99]
Rainbow parentheses works perfectly for Common Lisp without any issues but scheme which is a lisp dialect doesn't work. I can rename a .scm to .lisp and have the highlighting work but otherwise it doesn't.

**Comment by p00f** [comment]
CL and scheme are two different [filetypes](https://neovim.io/doc/user/options.html#'filetype')

**Comment by p00f** [comment]
Added scheme
